// Supabase Edge Function: weekly-program-cron
// Triggered by a GitHub Actions cron every Sunday. Auto-regenerates the coming week's program
// for every user who has opted in (user_settings.auto_regenerate_program = true), skipping
// anyone who already has an active program covering the new week (never clobbers a manually
// generated or hand-tweaked program).
//
// This is a server-side port of js/lib/{recovery,context,principles,program}.js — kept
// deliberately close to a 1:1 port so a program generated by the cron matches one generated by
// tapping "Regenerate" in the app. If those client files change, mirror the change here too.
//
// Required secrets: SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY (auto-provided), ANTHROPIC_API_KEY
// (same key coach-proxy uses), CRON_SECRET (shared secret checked against the GitHub Actions
// caller — this function has JWT verification disabled since no user is signed in).

import { createClient } from "npm:@supabase/supabase-js@2";

const MODEL = "claude-sonnet-4-6";
const ANTHROPIC_URL = "https://api.anthropic.com/v1/messages";
const MAX_TOKENS = 8000;

// ============================================================================
// js/lib/principles.js port (verbatim)
// ============================================================================
const COACHING_PRINCIPLES = `
EVIDENCE-BASED COACHING PRINCIPLES — these are FIRM GUARDRAILS. Do not violate the HARD RULES.
They reflect ACSM/NSCA position stands, Schoenfeld's volume/frequency work, RIR autoregulation
(Helms et al.), and Seiler's polarized-endurance research.

HARD RULES (never break these):
1. Every training-day session must fit ~60 minutes TOTAL, INCLUDING the warm-up and cool-down.
   Prioritize ruthlessly; if it won't fit, cut lower-priority work rather than overrun.
2. Do NOT program a conventional or sumo deadlift on the same day as a back squat, regardless of
   RPE. Heavy squat and heavy conventional/sumo deadlift are the two most axially demanding lifts
   and must be on different days. If a day includes back squats, any additional posterior-chain
   work that day must be a hip-hinge VARIATION with lower spinal load (e.g. Romanian deadlift,
   hip thrust, back extension) — never a conventional/sumo deadlift.
3. At most TWO heavy barbell compound lifts (squat / deadlift / bench / overhead press variants at
   RPE >= 7) in a single training day. Everything else that day is accessory work.
4. Do not prescribe routine training to failure on heavy compound barbell lifts. Most working
   sets sit at RPE 7–9 (1–3 reps in reserve).
5. Respect stated injuries/limitations strictly — always choose a pain-free variation.
6. When recovery is flagged yellow/red (elevated resting HR, suppressed HRV, acute:chronic load
   > ~1.3, or poor sleep), reduce volume/intensity or insert rest; do not push hard sessions.

WARM-UP & COOL-DOWN (required on every training day):
- Prescribe a specific warm-up (general raise + dynamic mobility + movement-specific ramp sets for
  that day's main lifts) and a specific cool-down (easy aerobic flush and/or targeted stretching
  and mobility), each with a duration in minutes. These count toward the 60-minute cap above.
- Tailor them to the session: a heavy lower-body day warms up hips/ankles and ramps the squat; a
  Zone 2 run cools down with an easy walk and calf/hip stretches.

COMBINING STRENGTH + CARDIO ON CARDIO DAYS:
- It's fine to place a short strength block BEFORE the cardio work on a cardio day, as long as the
  whole session (warm-up + strength + cardio + cool-down) still fits ~60 minutes. Always order
  strength before endurance when combined, to preserve strength quality (standard concurrent
  training practice), and keep the strength block modest so the cardio quality isn't wrecked.

ACCOUNTING FOR UNPLANNED ACTIVITY (e.g. hikes, pickup sports logged via Garmin):
- The client's Garmin activities include BOTH planned sessions and unplanned efforts. Treat every
  logged activity as real training stress — it counts toward weekly load and recovery.
- If a significant unplanned effort displaced a planned session (e.g. a long hike on a scheduled
  strength day), rebalance the remaining week: move the displaced session to a later, lighter slot
  rather than stacking hard work on top of accumulated fatigue, and drop lower-priority work if the
  week is now too dense.

PROGRAMMING GUIDELINES (strong defaults):
- Frequency: train each major movement pattern / muscle group ~2x per week when the schedule
  allows — superior to 1x for both strength and hypertrophy at matched volume.
- Volume: roughly 10–20 hard sets per muscle group per week for hypertrophy; start nearer the
  low end and progress. Strength emphasis uses lower reps (~1–6) at higher intensity, fewer sets.
- Progressive overload: nudge load/reps up gradually versus the client's RECENT logged working
  weights (typically <= ~2.5–5% per week on main lifts). Do not make large jumps.
- Autoregulate with explicit RPE/RIR targets on every prescribed exercise.
- Always ramp up to heavy compound sets with warm-up sets.
- Deload: program a lighter week (~40–60% of normal volume) roughly every 4–8 weeks, or sooner
  if fatigue is accumulating per the recovery indicators.

CARDIO / CONCURRENT TRAINING (for cardiovascular goals):
- Polarize: ~80% of cardio time easy (Zone 2 base) and ~20% hard (intervals). Build Zone 2
  volume; avoid parking most training in the moderate "gray zone" between Zone 2 and threshold.
- Both Zone 2 base and interval work drive VO2 max — include some of each across the week.
- Minimize interference: keep hard interval sessions away from heavy lower-body strength days
  (separate by a day, or place cardio after — not before — heavy leg work when same-day).
- Respect the WHO guideline of >= 150 min/week moderate-intensity (or equivalent).

BEGINNERS: emphasize technique and submaximal loads; full-body 2–3x/week is appropriate and
efficient. Progress conservatively.
`.trim();

const DAY_SCHEMA = `{
  "day_offset": number,      // 0 = today, 1 = tomorrow, ... 6
  "focus": string,           // short, e.g. "Lower strength", "Zone 2 cardio", "Rest"
  "is_rest_day": boolean,
  "duration_min": number,    // estimated TOTAL minutes incl. warm-up + cool-down (0 for rest days)
  "warmup": [                // individual warm-up movements ([] for rest days)
    { "name": string, "detail": string }
  ],
  "warmup_min": number,
  "cooldown": [
    { "name": string, "detail": string }
  ],
  "cooldown_min": number,
  "exercises": [
    { "name": string, "sets": number, "reps": string, "rest_seconds": number, "rpe_target": number, "notes": string }
  ],
  "rationale": string
}`;

const GENERATE_PROMPT = `${COACHING_PRINCIPLES}

You are an AI personal trainer building a client's 7-day training program
(a rolling week starting today, day_offset 0). Use their full context: profile (experience,
injuries, equipment, SCHEDULE / days-per-week available, preferences, goals), baseline (anchor
starting loads to it), recovery indicators, recent Garmin data and logs.

Rules:
- Return EXACTLY 7 day objects, day_offset 0 through 6, in order.
- Honor their schedule: include rest days so training days match how many days/week they can train.
- Every training day MUST include a warm-up and cool-down, EACH broken into a list of specific,
  individually-named movements (not one paragraph) — e.g. warmup: [{"name":"Leg swings","detail":"10 each leg"},
  {"name":"Bodyweight squats","detail":"2x10"}]. Each movement must be a real, searchable exercise
  name so the client can look up its form. The total (warm-up + work + cool-down) must fit ~60 minutes.
- Balance strength with structured cardio when they have a cardiovascular goal (Zone 2 base volume
  plus some interval work — the two levers for VO2 max), and avoid burying everything in the
  moderate "gray zone".
- Respect injuries strictly. Apply progressive overload vs. their recent logged working weights.
  For any accessory the client has logged before, prescribe based on their last logged weight.
- If recovery is flagged yellow/red, reduce volume/intensity and/or add rest.
- Keep every "notes" field to one short phrase. Be concise so the whole plan fits.

Respond with ONLY a JSON object (no markdown fences, no commentary):
{ "days": [ ${DAY_SCHEMA} ] }`;

// ============================================================================
// js/lib/recovery.js port
// ============================================================================
function daysAgo(dateStr: string, today: Date): number {
  return Math.floor((today.getTime() - new Date(dateStr + "T00:00:00Z").getTime()) / 86400000);
}
function avg(nums: (number | null | undefined)[]): number | null {
  const clean = nums.filter((n): n is number => typeof n === "number" && !Number.isNaN(n));
  if (!clean.length) return null;
  return clean.reduce((a, b) => a + b, 0) / clean.length;
}
function windowValues(rows: any[], field: string, fromDaysAgo: number, toDaysAgo: number, today: Date): number[] {
  return rows
    .filter((r) => {
      const d = daysAgo(r.date, today);
      return d >= fromDaysAgo && d < toDaysAgo;
    })
    .map((r) => r[field])
    .filter((v) => typeof v === "number");
}
function effectiveLoad(a: any): number | null {
  if (typeof a.training_load === "number") return a.training_load;
  if (typeof a.duration_seconds !== "number") return null;
  const minutes = a.duration_seconds / 60;
  const hr = a.avg_hr;
  let factor = 0.8;
  if (typeof hr === "number") {
    if (hr >= 150) factor = 2.0;
    else if (hr >= 130) factor = 1.3;
    else if (hr >= 110) factor = 0.9;
    else factor = 0.6;
  }
  return Math.round(minutes * factor);
}
function computeRecoveryStatus({ wellness = [], health = [], activities = [] }: { wellness: any[]; health: any[]; activities: any[] }, today: Date) {
  const hasAnyData = wellness.length > 0 || health.length > 0 || activities.length > 0;
  if (!hasAnyData) {
    return { level: "unknown", reasons: ["No wearable data connected yet."], metrics: {} };
  }
  const reasons: string[] = [];
  let flagCount = 0;
  const loadedActivities = activities.map((a) => ({ ...a, _load: effectiveLoad(a) }));

  const rhr7 = avg(windowValues(wellness, "resting_hr", 0, 7, today));
  const rhrBaseline = avg(windowValues(wellness, "resting_hr", 7, 37, today));
  const rhrElevatedDays = wellness.filter((r) => {
    const d = daysAgo(r.date, today);
    return d >= 0 && d < 7 && typeof r.resting_hr === "number" && rhrBaseline && r.resting_hr > rhrBaseline + 3;
  }).length;
  let rhrFlag = false;
  if (rhr7 != null && rhrBaseline != null && rhrElevatedDays >= 3) {
    rhrFlag = true;
    reasons.push(`Resting heart rate has been elevated on ${rhrElevatedDays} of the last 7 days (avg ${rhr7.toFixed(1)} bpm vs your ~${rhrBaseline.toFixed(1)} bpm baseline).`);
  }
  if (rhrFlag) flagCount++;

  const sleep7 = avg(windowValues(wellness, "sleep_seconds", 0, 7, today));
  const sleepBaseline = avg(windowValues(wellness, "sleep_seconds", 7, 37, today));
  let sleepFlag = false;
  if (sleep7 != null && sleepBaseline != null) {
    const deltaMin = (sleep7 - sleepBaseline) / 60;
    if (deltaMin <= -30) {
      sleepFlag = true;
      reasons.push(`Sleep is trending down — averaging ${(sleep7 / 3600).toFixed(1)}h/night this week vs your ~${(sleepBaseline / 3600).toFixed(1)}h baseline.`);
    }
  }
  if (sleepFlag) flagCount++;

  const hrv7 = avg(windowValues(health, "hrv_avg_ms", 0, 7, today));
  const hrvBaseline = avg(windowValues(health, "hrv_avg_ms", 7, 37, today));
  const hrvSuppressedDays = health.filter((r) => {
    const d = daysAgo(r.date, today);
    return d >= 0 && d < 7 && typeof r.hrv_avg_ms === "number" && hrvBaseline && r.hrv_avg_ms < hrvBaseline * 0.9;
  }).length;
  let hrvFlag = false;
  if (hrv7 != null && hrvBaseline != null && hrvSuppressedDays >= 3) {
    hrvFlag = true;
    reasons.push(`HRV has been suppressed on ${hrvSuppressedDays} of the last 7 nights (avg ${hrv7.toFixed(0)}ms vs your ~${hrvBaseline.toFixed(0)}ms baseline).`);
  }
  if (hrvFlag) flagCount++;

  const acute = avg(windowValues(loadedActivities, "_load", 0, 7, today));
  const chronic = avg(windowValues(loadedActivities, "_load", 0, 28, today));
  let loadRatio: number | null = null;
  let loadFlag = false;
  let loadFlagLevel: string | null = null;
  if (acute != null && chronic != null && chronic > 0) {
    loadRatio = acute / chronic;
    if (loadRatio > 1.5) {
      loadFlag = true;
      loadFlagLevel = "red";
      reasons.push(`Training load has spiked — your 7-day load is running ${loadRatio.toFixed(2)}x your 28-day average.`);
    } else if (loadRatio > 1.3) {
      loadFlag = true;
      loadFlagLevel = "yellow";
      reasons.push(`Training load ratio is ${loadRatio.toFixed(2)}x (acute:chronic) — trending high.`);
    }
  }
  if (loadFlag) flagCount++;

  let level = "green";
  if (flagCount >= 2 || loadFlagLevel === "red") level = "red";
  else if (flagCount === 1) level = "yellow";
  if (level === "green" && !reasons.length) reasons.push("Resting HR, sleep, HRV, and training load all look within your normal range.");

  return {
    level,
    reasons,
    metrics: {
      resting_hr_7d: rhr7, resting_hr_baseline: rhrBaseline,
      sleep_7d_hours: sleep7 != null ? sleep7 / 3600 : null, sleep_baseline_hours: sleepBaseline != null ? sleepBaseline / 3600 : null,
      hrv_7d: hrv7, hrv_baseline: hrvBaseline,
      acute_load: acute, chronic_load: chronic, load_ratio: loadRatio,
    },
  };
}

// ============================================================================
// js/lib/context.js port
// ============================================================================
const CHAT_SUMMARY_MAX_CHARS = 1200;
function trimProfileForPrompt(profile: any) {
  const trimmed = { ...profile };
  if (typeof trimmed.chat_summary === "string" && trimmed.chat_summary.length > CHAT_SUMMARY_MAX_CHARS) {
    trimmed.chat_summary = `...${trimmed.chat_summary.slice(-CHAT_SUMMARY_MAX_CHARS)}`;
  }
  if (Array.isArray(trimmed.cardio_reports) && trimmed.cardio_reports.length) {
    trimmed.cardio_reports = [trimmed.cardio_reports[trimmed.cardio_reports.length - 1]];
  }
  return trimmed;
}
function slimActivity(a: any) {
  const { id, type, date, name, duration_seconds, distance_meters, avg_hr, max_hr, calories, training_load } = a;
  return { id, type, date, name, duration_seconds, distance_meters, avg_hr, max_hr, calories, training_load };
}
function slimWellness(w: any) {
  const { date, resting_hr, sleep_seconds, steps } = w;
  return { date, resting_hr, sleep_seconds, steps };
}
function slimHealth(h: any) {
  const { date, vo2max_running, vo2max_cycling, hrv_avg_ms, hrv_status, intensity_minutes_moderate, intensity_minutes_vigorous } = h;
  return { date, vo2max_running, vo2max_cycling, hrv_avg_ms, hrv_status, intensity_minutes_moderate, intensity_minutes_vigorous };
}

function contextToPromptText(ctx: any): string {
  return `
TODAY'S DATE: ${ctx.today}
UNITS: all weights are in ${ctx.units}. Use ${ctx.units} in any prescriptions or numbers you give.
${ctx.latestBodyWeight ? `CURRENT BODY WEIGHT: ${ctx.latestBodyWeight.weight} ${ctx.latestBodyWeight.weight_unit || ctx.units} (logged ${ctx.latestBodyWeight.date})` : ""}

TRAINER PROFILE:
${JSON.stringify(trimProfileForPrompt(ctx.profile))}

GOALS:
${JSON.stringify(ctx.goals)}

RECOVERY INDICATORS (computed locally, trust these numbers):
level: ${ctx.recovery.level}
reasons: ${ctx.recovery.reasons.join(" | ")}
metrics: ${JSON.stringify(ctx.recovery.metrics)}

LAST 14 DAYS OF GARMIN ACTIVITIES (includes BOTH planned sessions and any unplanned efforts like
hikes — treat every one as real training stress and reconcile the plan against what actually happened):
${JSON.stringify(ctx.last14Activities.map(slimActivity))}

LAST 14 DAYS OF WELLNESS (sleep, resting HR, steps):
${JSON.stringify(ctx.last14Wellness.map(slimWellness))}

LAST 14 DAYS OF HEALTH (VO2 max, HRV, intensity minutes):
${JSON.stringify(ctx.last14Health.map(slimHealth))}

LAST 14 DAYS OF LOGGED EXERCISES:
${JSON.stringify(ctx.last14Logs)}

TODAY'S PLANNED WORKOUT (if already generated):
${JSON.stringify(ctx.todaysWorkout)}

MOST RECENT WEEKLY REVIEW:
${JSON.stringify(ctx.latestReview)}
`.trim();
}

// ============================================================================
// js/lib/program.js port
// ============================================================================
function todayStr(d: Date): string {
  return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, "0")}-${String(d.getUTCDate()).padStart(2, "0")}`;
}
function addDays(dateStr: string, n: number): string {
  const d = new Date(dateStr + "T00:00:00Z");
  d.setUTCDate(d.getUTCDate() + n);
  return todayStr(d);
}
function normalizeMovements(value: any) {
  if (Array.isArray(value)) {
    return value
      .map((m) => (typeof m === "string" ? { name: m, detail: "" } : { name: m?.name || "", detail: m?.detail || "" }))
      .filter((m) => m.name);
  }
  if (typeof value === "string" && value.trim()) return [{ name: value.trim(), detail: "" }];
  return [];
}
function toWorkoutEntry(programId: string, startDate: string, day: any) {
  const date = addDays(startDate, day.day_offset);
  return {
    date,
    program_id: programId,
    day_offset: day.day_offset,
    focus: day.focus || (day.is_rest_day ? "Rest" : "Training"),
    is_rest_day: !!day.is_rest_day,
    duration_min: day.duration_min || null,
    warmup: normalizeMovements(day.warmup),
    warmup_min: day.warmup_min || null,
    cooldown: normalizeMovements(day.cooldown),
    cooldown_min: day.cooldown_min || null,
    exercises: (day.exercises || []).map((e: any) => ({ ...e, completed_sets: [] })),
    rationale: day.rationale || "",
    status: day.is_rest_day ? "rest" : "planned",
    generated_at: new Date().toISOString(),
  };
}

/** Same brace-matching JSON extraction as js/supabase/anthropic.js. */
function extractJSON(text: string): any {
  const fenced = text.trim().replace(/^```(?:json)?/i, "").replace(/```$/, "").trim();
  try {
    return JSON.parse(fenced);
  } catch {
    /* fall through */
  }
  const startIdx = (() => {
    const obj = text.indexOf("{");
    const arr = text.indexOf("[");
    if (obj === -1) return arr;
    if (arr === -1) return obj;
    return Math.min(obj, arr);
  })();
  if (startIdx === -1) return null;
  const open = text[startIdx];
  const close = open === "{" ? "}" : "]";
  let depth = 0;
  let inStr = false;
  let escaped = false;
  for (let i = startIdx; i < text.length; i++) {
    const ch = text[i];
    if (inStr) {
      if (escaped) escaped = false;
      else if (ch === "\\") escaped = true;
      else if (ch === '"') inStr = false;
      continue;
    }
    if (ch === '"') inStr = true;
    else if (ch === open) depth++;
    else if (ch === close) {
      depth--;
      if (depth === 0) {
        try {
          return JSON.parse(text.slice(startIdx, i + 1));
        } catch {
          return null;
        }
      }
    }
  }
  return null;
}

// ============================================================================
// Main handler
// ============================================================================
const corsHeaders = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "content-type, x-cron-secret" };

function json(obj: unknown, status: number): Response {
  return new Response(JSON.stringify(obj), { status, headers: { ...corsHeaders, "content-type": "application/json" } });
}

function currentMonthKey(d: Date): string {
  return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, "0")}`;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  const cronSecret = Deno.env.get("CRON_SECRET");
  if (!cronSecret || req.headers.get("X-Cron-Secret") !== cronSecret) {
    return json({ error: "unauthorized" }, 401);
  }

  const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
  const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
  const anthropicKey = Deno.env.get("ANTHROPIC_API_KEY")!;
  const db = createClient(supabaseUrl, serviceKey);

  const now = new Date();
  const today = todayStr(now);
  const month = currentMonthKey(now);

  const { data: optedIn, error: optedInErr } = await db
    .from("user_settings")
    .select("user_id, monthly_token_cap")
    .eq("auto_regenerate_program", true);
  if (optedInErr) return json({ error: "query_failed", detail: optedInErr.message }, 500);

  const results: Record<string, string> = {};

  for (const row of optedIn || []) {
    const uid = row.user_id;
    try {
      // Skip if quota already exhausted this month.
      const { data: usageRow } = await db.from("usage").select("input_tokens, output_tokens, requests").eq("user_id", uid).eq("month", month).maybeSingle();
      const used = (usageRow?.input_tokens ?? 0) + (usageRow?.output_tokens ?? 0);
      const cap = row.monthly_token_cap ?? 300000;
      if (used >= cap) {
        results[uid] = "skipped: quota exceeded";
        continue;
      }

      const { data: profileRow } = await db.from("profiles").select("data").eq("user_id", uid).maybeSingle();
      const profile = profileRow?.data ?? {};

      // Skip if an active program already covers this week — never clobber a program the user
      // already has, whether auto-generated earlier or hand-tweaked.
      const ap = profile.active_program;
      if (ap && today >= ap.start_date && today <= addDays(ap.start_date, 6)) {
        results[uid] = "skipped: active program already covers this week";
        continue;
      }

      const since37 = addDays(today, -37);
      const since14 = addDays(today, -14);

      const [{ data: goalsRows }, { data: wellnessRows }, { data: healthRows }, { data: activitiesRows }, { data: logRows }, { data: reviewRows }, { data: bodyRows }] =
        await Promise.all([
          db.from("goals").select("goal").eq("user_id", uid),
          db.from("garmin_wellness").select("data").eq("user_id", uid).gte("date", since37),
          db.from("garmin_health").select("data").eq("user_id", uid).gte("date", since37),
          db.from("garmin_activities").select("data").eq("user_id", uid).gte("date", since37),
          db.from("exercise_logs").select("entry").eq("user_id", uid).gte("date", since14),
          db.from("weekly_reviews").select("review").eq("user_id", uid).order("week", { ascending: false }).limit(1),
          db.from("body_metrics").select("date, weight, weight_unit").eq("user_id", uid).order("date", { ascending: false }).limit(1),
        ]);

      const goals = (goalsRows || []).map((r) => r.goal);
      const wellness = (wellnessRows || []).map((r) => r.data);
      const health = (healthRows || []).map((r) => r.data);
      const activities = (activitiesRows || []).map((r) => r.data);
      const exerciseLog = (logRows || []).map((r) => r.entry);
      const latestReview = reviewRows && reviewRows[0] ? reviewRows[0].review : null;
      const latestBodyWeight = bodyRows && bodyRows[0] ? bodyRows[0] : null;

      const recovery = computeRecoveryStatus({ wellness, health, activities }, now);
      const last14Activities = activities.filter((a: any) => daysAgo(a.date, now) < 14);
      const last14Wellness = wellness.filter((w: any) => daysAgo(w.date, now) < 14);
      const last14Health = health.filter((h: any) => daysAgo(h.date, now) < 14);

      const ctx = {
        today,
        units: profile.units || "lb",
        latestBodyWeight,
        profile,
        goals,
        recovery,
        last14Activities,
        last14Wellness,
        last14Health,
        last14Logs: exerciseLog,
        todaysWorkout: null,
        latestReview,
      };

      const userMessage = `Build my 7-day program starting today (${today}).\n\n${contextToPromptText(ctx)}`;
      const anthropicRes = await fetch(ANTHROPIC_URL, {
        method: "POST",
        headers: { "content-type": "application/json", "x-api-key": anthropicKey, "anthropic-version": "2023-06-01" },
        body: JSON.stringify({ model: MODEL, max_tokens: MAX_TOKENS, system: GENERATE_PROMPT, messages: [{ role: "user", content: userMessage }] }),
      });
      if (!anthropicRes.ok) {
        results[uid] = `error: anthropic ${anthropicRes.status}`;
        continue;
      }
      const anthropicJson = await anthropicRes.json();
      const inTok = anthropicJson?.usage?.input_tokens ?? 0;
      const outTok = anthropicJson?.usage?.output_tokens ?? 0;
      await db.from("usage").upsert(
        {
          user_id: uid,
          month,
          input_tokens: (usageRow?.input_tokens ?? 0) + inTok,
          output_tokens: (usageRow?.output_tokens ?? 0) + outTok,
          requests: (usageRow?.requests ?? 0) + 1,
          updated_at: new Date().toISOString(),
        },
        { onConflict: "user_id,month" }
      );

      const text = (anthropicJson.content || []).map((b: any) => b.text || "").join("");
      const parsed = extractJSON(text);
      if (!parsed || !Array.isArray(parsed.days)) {
        results[uid] = "error: coach reply was not valid JSON";
        continue;
      }

      const programId = `prog-${Date.now()}-${uid.slice(0, 8)}`;
      const entries = parsed.days.slice(0, 7).map((d: any) => toWorkoutEntry(programId, today, d));
      const rows = entries.map((e: any) => ({ user_id: uid, date: e.date, program_id: e.program_id, day: e }));
      const { error: upsertErr } = await db.from("workouts").upsert(rows, { onConflict: "user_id,date" });
      if (upsertErr) {
        results[uid] = `error: workouts upsert failed: ${upsertErr.message}`;
        continue;
      }

      await db.from("profiles").update({
        data: { ...profile, active_program: { program_id: programId, start_date: today, generated_at: new Date().toISOString() } },
        updated_at: new Date().toISOString(),
      }).eq("user_id", uid);

      results[uid] = `generated: ${entries.length} days`;
    } catch (e) {
      results[uid] = `error: ${String(e)}`;
    }
  }

  return json({ ok: true, today, processed: Object.keys(results).length, results }, 200);
});
